gantt
    title Team 4513 2025 Project Management
    dateFormat  YYYY-MM-DD
    excludes Friday Sunday 2025-01-20 2025-02-14 2025-02-17 2025-03-13 2025-03-14 2025-03-21

    section Base design
    Rules released   : bas1, 2025-01-04, 1d
    Decide what      : bas2, after bas1  , 1d
    Decide how       : bas3, after bas2  , 5d

    commission robot        : soft5, after ele5 soft4, 1d
    test new robot code     : soft6, after soft5, 2d
    test robot with driver  : soft7, after soft6, 5d
    new joystick commands   : soft8, after soft6, 5d

    section Salem Competition
    load           : comp1, 2025-02-26, 1d
    travel         : comp2, after comp1, 1d
    compete        : comp3, after comp2, 2025-03-01
    Rules released   : bas1, 2025-01-04, 1d
    Decide what      : bas2, after bas1  , 1d
    Decide how       : bas3, after bas2  , 5d

    section Mechanical
    mechanical CAD   : mech1, after bas3 , 5d
    robot CAD        : mech2, after mech1, 5d
    build base robot : mech3, after mech2, 3d
    build mechanisms : mech4, after mech3, 4d

    section Electrical
    place components  : ele4, after mech4, 2d
    wire robot        : ele5, after ele4, 5d

    section Field
    build target       : field1, after bas1, 5d
    built load station : field2, after field1, 5d
    build end station  : field3, after field2, 5d

    section Software
    setup library and IDEs  : soft1, after bas1,5d
    setup mechanism folders : soft2, after bas2, 4d
    write new code          : soft3, after soft2, 10d
    test code               : soft4, after soft3, 5d
    commission robot        : soft5, after ele5 soft4, 1d
    test new robot code     : soft6, after soft5, 2d
    test robot with driver  : soft7, after soft6, 5d
    new joystick commands   : soft8, after soft6, 5d

    section Salem Competition
    load           : comp1, 2025-02-26, 1d
    travel         : comp2, after comp1, 1d
    compete        : comp3, after comp2, 2025-03-01
